package io.github.anjoismysign.blobproperties.entity;

public enum ItemType {
    PUBLIC_PROPERTY_DOOR_MANAGER,
    PRIVATE_PROPERTY_DOOR_MANAGER,
    PUBLIC_PROPERTY_CONTAINER_MANAGER,
    PRIVATE_PROPERTY_CONTAINER_MANAGER
}
