package blobproperties.enums;

public enum ItemType {
    PUBLICPROPERTYDOORMANAGER,
    PRIVATEPROPERTYDOORMANAGER,
    PUBLICPROPERTYCONTAINERMANAGER,
    PRIVATEPROPERTYCONTAINERMANAGER,
    PUBLICPROPERTYCONTAINER
}