name: BlobProperties
main: io.github.anjoismysign.blobproperties.BlobProperties
version: ${project.version}
author: anjoismysign
api-version: 1.21.11
depend: [ BlobLib ]
softdepend: [AlternativeSaving, BlobTycoon]
commands:
  properties:
    description: base command
    aliases: [ bp ]